# Generated by Django 3.2.3 on 2021-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_img', models.ImageField(upload_to='pic')),
                ('port_name', models.CharField(max_length=20)),
                ('port_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
