# Generated by Django 3.2.3 on 2021-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
