# Generated by Django 3.2.3 on 2021-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_members',
            name='team_img',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
