# Generated by Django 3.2.3 on 2021-06-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_board_members_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_members',
            old_name='team_img',
            new_name='images',
        ),
    ]
