# Generated by Django 3.2.3 on 2021-06-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_team_img_board_members_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('txt', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
    ]
