# Generated by Django 3.2.3 on 2021-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
