# Generated by Django 3.2.3 on 2021-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_members',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='board_members',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
