# Generated by Django 3.2.3 on 2021-06-10 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name_popup',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
